package com.drools.demo.point

import com.drools.point.domain.Point;

rule subBackNumsPoint
	// 发生退货，扣减10分
	salience 10
	lock-on-active true
	when
		$point : Point(backNums >= 1)
	then
		$point.setPoint($point.getPoint()-10);
		$point.recordPointLog($point.getUserName(),"subBackNumsPoint");
end

rule subBackMondyPoint
	// 退货金额大于100，扣减100分
	salience 9
	lock-on-active true
	when
		$point : Point(backMoney >= 100)
	then
		$point.setPoint($point.getPoint()-10);
		$point.recordPointLog($point.getUserName(),"subBackMondyPoint");
end